[private]
default:
  @just --list

[private]
setup:
  pnpm install

assets: setup
  pnpm run build

fmt: setup
  pnpm run fmt

check: setup assets
  pnpm run check

test: setup
  pnpm run test

verify: fmt check test

clean:
  pnpm cache delete
